---
title: "Analysis"
format: pdf
editor: visual
---

## Setup

```{r setup}
Functions = list()

pacman::p_load(tidyverse,janitor,readxl,writexl,diverse,glue,ggimage,ggthemes,extrafont,ggtext,ragg,hrbrthemes)

Functions$matrix_preprocess <- function(matrix) {
  matrix %>%
    rename_with(~str_remove(.x,"CPA_")) %>%
    rename_with(~str_replace(.x,"-|_","-")) %>%
    rename_with(~str_replace(.x,"VL","L")) %>%
    mutate(Buyer = `...1` %>%
             str_remove("CPA_") %>%
             str_replace("-|_","-") %>%
             str_replace("VL","L"),
           .before = `...1`
           ) %>%
    select(-`...1`) %>%
    pivot_longer(cols = 2:last_col(),
               names_to = "Seller",
               values_to = "value") %>%
    mutate(
  Buyer = ifelse(Buyer %>% str_detect("A"),
                 "A",
                 Buyer),
  Seller = ifelse(Seller %>% str_detect("A"),
                 "A",
                 Seller)
) %>%
  summarise(value = sum(value),
            .by = c(Buyer, Seller))
}

Functions$diversity <- function(db,entity,trait,value,d_matrix){
  {{ db }} %>%
    mutate({{ value }} := {{ value }} / sum({{ value }}),
           .by = {{ entity }}) -> db_p

  db_p %>%
    reframe(i = expand.grid({{ trait }},{{ trait }}),
            .by = {{ entity }}) %>%
    unnest(i) %>%
    rename(
      i = Var1,
      j = Var2,
    ) %>%
    left_join(
      db_p %>% transmute(
      {{ entity }},
      i = {{ trait }},
      p_i = {{ value }}
    )) %>%
    left_join(
      db_p %>% transmute(
      {{ entity }},
      j = {{ trait }},
      p_j = {{ value }}
    )) %>%
    mutate(d = map2_dbl(i,j,~{{ d_matrix }}[.y, .x])) %>%
    summarise(.by = {{ entity }},
              RS = sum(p_i * p_j * d),
              True_RS = 1 / (1 - RS)
    )
  
}
```

## Import data

```{r}
codex <- read_excel("Codex.xlsx")

db_ATECO <- read_excel("italia 2015-2018.xlsx", 
    sheet = "2015") %>%
  Functions$matrix_preprocess() %>%
  mutate(Country = "Italy",
         Year = "2015") %>%
  add_row(read_excel("italia 2015-2018.xlsx", 
    sheet = "2018") %>%
  Functions$matrix_preprocess() %>%
  mutate(Country = "Italy",
         Year = "2018")) %>%
  add_row(read_excel("germania 2015-2018.xlsx", 
    sheet = "2015") %>%
  Functions$matrix_preprocess() %>%
  mutate(Country = "Germany",
         Year = "2015")) %>%
  add_row(read_excel("germania 2015-2018.xlsx", 
    sheet = "2018") %>%
  Functions$matrix_preprocess() %>%
  mutate(Country = "Germany",
         Year = "2018")) %>%
  add_row(read_excel("Francia 2015-2018.xlsx", 
    sheet = "2015") %>%
  Functions$matrix_preprocess() %>%
  mutate(Country = "France",
         Year = "2015"))%>%
  add_row(read_excel("Francia 2015-2018.xlsx", 
    sheet = "2018") %>%
  Functions$matrix_preprocess() %>%
  mutate(Country = "France",
         Year = "2018"))

db_ECOS <- expand.grid(Buyer = codex$ATECO,Seller = codex$ATECO) %>%
  left_join(db_ATECO) %>%
  left_join(codex %>%
              transmute(Buyer = ATECO,
                        ECOS_Buyer = Ecosystem,
                        w_Buyer = w)) %>%
  left_join(codex %>%
              transmute(Seller = ATECO,
                        ECOS_Seller = Ecosystem,
                        w_Seller = w)) %>%
  transmute(Buyer = ECOS_Buyer,
            Seller = ECOS_Seller,
            value,
            w_Buyer,
            w_Seller,
            Year,
            Country) %>%
  summarise(.by = c(Buyer, Seller, Year, Country),
            value = sum(value*w_Buyer*w_Seller))
```

## Disparity matrix

```{r}
db_ECOS %>%
  select(Buyer,Seller,value) %>%
  summarise(.by = c(Buyer, Seller),
            value = sum(value)) %>%
  pivot_wider(names_from = Seller,
              values_from = value) %>%
  column_to_rownames("Buyer") %>%
  as.matrix() %>%
  dist(method = "cosine", by_rows = T,
       diag = T, upper = T) %>%
  as.matrix() -> d_ECOS
writexl::write_xlsx(d_ECOS %>% as_tibble(rownames = "Ecosystem"),"dist_ECOS.xlsx")

naive_d_ECOS <- matrix(1,
                       nrow=nrow(d_ECOS),
                       ncol=ncol(d_ECOS))
diag(naive_d_ECOS) <- 0

db_ATECO %>%
  select(Buyer,Seller,value) %>%
  summarise(.by = c(Buyer, Seller),
            value = sum(value)) %>%
  pivot_wider(names_from = Seller,
              values_from = value) %>%
  column_to_rownames("Buyer") %>%
  data.matrix() %>%
  dist(method = "cosine", by_rows = T,
       diag = T, upper = T) %>%
  as.matrix() -> d_ATECO
writexl::write_xlsx(d_ATECO %>% as_tibble(rownames = "ATECO"),"dist_ATECO.xlsx")
```

## Automated tables: Selling

```{r}

results = list()

results$Seller_div = tibble(
  Year = NA,
  Country = NA,
  Seller = NA,
  RS = NA,
  True_RS = NA
)

for (Y in db_ECOS$Year %>% unique) {
  for (G in db_ECOS$Country %>% unique) {
    
    db_ECOS %>%
      filter(Year == Y,
             Country == G
             ) %>%
      Functions$diversity(Seller,Buyer,value,d_ECOS) %>%
      add_column(Year = Y,
                 Country = G) %>%
      add_row(results$Seller_div,.) -> results$Seller_div
  }
}

results$Seller_div %>%
  drop_na() %>%
  select(-RS) %>%
  write_xlsx("Seller_Diversity.xlsx")
```

## Automated tables: Selling

```{r}

results$Buyer_div = tibble(
  Year = NA,
  Country = NA,
  Buyer = NA,
  RS = NA,
  True_RS = NA
)

for (Y in db_ECOS$Year %>% unique) {
  for (G in db_ECOS$Country %>% unique) {
    
    db_ECOS %>%
      filter(Year == Y,
             Country == G
             ) %>%
      Functions$diversity(Buyer,Seller,value,d_ECOS) %>%
      add_column(Year = Y,
                 Country = G) %>%
      add_row(results$Buyer_div,.) -> results$Buyer_div
  }
}

G = NULL
Y = NULL

results$Buyer_div %>%
  drop_na() %>%
  select(-RS) %>%
  write_xlsx("Buyer_Diversity.xlsx")
```

# Figures

```{r}
results$Seller_div %>%
  select(-RS) %>%
  rename(Seller_Diversification = True_RS,
         Ecosystem = Seller) %>%
  left_join(results$Buyer_div %>%
              select(-RS) %>%
  rename(Buyer_Diversification = True_RS,
         Ecosystem = Buyer
         )) %>%
  left_join(
(db_ECOS %>%
  pivot_longer(cols = c(Buyer,Seller),
               values_to = "Ecosystem") %>%
   mutate(Self = value/sum(value),
         .by = c(Country,Year,Ecosystem)) %>%
  filter(Self == lag(Self,1),
         value > 0) %>%
  select(-value, -name)
)) %>%
  mutate(Country = Country %>% factor(levels = c("Germany",
                                                 "France",
                                                 "Italy"))) %>%
  drop_na() %>%
  adorn_rounding(3) -> results$full
```

```{r}
pacman::p_load(ggimage)

results$full %>%
  select(where(is.numeric)) %>%
  cor() %>%
  corrplot::corrplot(method="color",
                     type="upper",
                     addCoef.col = "goldenrod", # text color
                     tl.col="black", tl.srt=45,
                     cl.pos = "n",
                     tl.cex = 1)
  

results$full %>%
    ggplot() +
  geom_label(aes(x = Seller_Diversification,
                y = Buyer_Diversification,
                label = Ecosystem,
                fill = Self),
             color = "black", alpha = 0.5,
            size = 1.5) +
  scale_y_continuous(position = "right") +
  scale_fill_gradient(low="gold", high="magenta") +
  theme_dark() +
  theme(
    legend.position = "top",
    legend.direction = "horizontal",
    legend.box.margin = margin(-5, 0, -5, 0),
    strip.placement = 'outside'
  ) +
  guides(fill = guide_colorbar(barwidth = 30)) +
  xlab("Economic Ubiquity") +
  ylab("Financial Equality") +
  facet_grid(Country ~ Year, switch = "y")
  
    
ggsave("analysis.png")
```

```{r}
results$full %>%
  rename(Ubiquity = Seller_Diversification,
         Equality = Buyer_Diversification) %>%
  pivot_wider(
    names_from = Year, 
  values_from = c(Ubiquity,Equality,Self),
  names_sep = "_"
  ) %>%
  ggplot() +
  theme_economist() +
#  geom_segment(aes(x=x, xend=x, y=value1, yend=value2), color="grey") +
  geom_point(aes(x=Ubiquity_2015, y=Country,
                 size = Self_2015), color="orange",) +
  geom_point(aes(x=Ubiquity_2018, y=Country,
                 size = Self_2018), color="purple") +
  scale_y_discrete(limits = c("Italy", "France", "Germany"))+
  theme(
    axis.title.y = element_blank(),
    legend.position = "none",
  ) +
  xlab("Economic Ubiquity") +
  facet_wrap(~ Ecosystem,
             nrow = 7,
             ncol = 2)
  
  
ggsave("lollipop.png")
```

```{r}
results$full %>%
  rename(Ubiquity = Seller_Diversification,
         Equality = Buyer_Diversification) %>%
  pivot_wider(
    names_from = Year, 
  values_from = c(Ubiquity,Equality,Self),
  names_sep = "_"
  ) %>%
  ggplot() +
  geom_segment(aes(x = Equality_2015, xend = Equality_2018,
                   y = Ubiquity_2015, yend = Ubiquity_2018,
                   color = Country),
                  arrow = arrow(length = unit(.06, "cm"),
                                angle = 25,
                                type="closed"),
              linewidth = 1.2,
              lineend = "round",
              linejoin = "mitre") +
  scale_color_manual(values = c("gold","blue4","springgreen1")) +
  theme_dark() +
    theme(
    legend.position = "top",
    legend.title = element_blank()
  ) +
  xlab("Shift in Financial Equality (2015-18)") +
  ylab("Shift in Economic Ubiquity (2015-18)") +
  facet_wrap(~ Ecosystem,
             nrow = 2,
             ncol = 7)

ggsave("arrows.png",
        width = 10, height = 4)
```
